# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 早川智将的小窝
email:zhengnobita2589@163.com
description: >- # this means to ignore newlines until "baseurl:"
  早川智将的个人主页,或许兼做博客用途.
twitter_username: NobitaZhen25412
github_username: Jesse5800-2
minimal_mistakes_skin: air
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "早川智将"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "如果没有奇迹的话,那就,去创造奇迹吧,少年."
  links:
    - label: "旧的纯手作主页"
      icon: "fas fa-fw fa-link"
      url: "https://jesse5800-2.github.io/kuzuhykw-studio/"
    - label: "蓝鸟"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/NobitaZhen22128"
    - label: "猫鱿鱼"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Jesse5800-2"
    - label: "比利♂比利"
      icon: "fab fa-fw fa-bilibili"
      url: "https://space.bilibili.com/3493291999890101"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/NobitaZhen22128"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "哔哩哔哩"
      icon: "fab fa-fw fa-bilibili"
      url: "https://space.bilibili.com/3493291999890101"
    - label: "Pixiv"
      icon: "fas fa-fw fa-image"
      url: "https://www.pixiv.net/users/108076015"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
